version: '3'

services:
  postgres:
    image: postgres:15-alpine
    container_name: azeroth-data_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5333:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - data_network

  minio:
    image: minio/minio
    container_name: azeroth-data_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - data_network

  dagster_webserver:
    build:
      context: ./data_pipeline
      dockerfile: Dockerfile
    container_name: dagster_webserver
    restart: always
    environment:
      DAGSTER_POSTGRES_USER: ${POSTGRES_USER}
      DAGSTER_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DAGSTER_POSTGRES_DB: ${POSTGRES_DB}
      
      BLIZZARD_CLIENT_ID: ${BLIZZARD_CLIENT_ID}
      BLIZZARD_CLIENT_SECRET: ${BLIZZARD_CLIENT_SECRET}
      
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      
      DAGSTER_CURRENT_IMAGE_NAME: "azeroth-dagster-image"
    volumes:
      - ./data_pipeline:/opt/dagster/app
    ports:
      - "3000:3000"
    command: dagster-webserver -h 0.0.0.0 -p 3000 -w config/workspace.yaml
    depends_on:
      - postgres
      - minio
    networks:
      - data_network
  
  dagster_daemon:
    build:
      context: ./data_pipeline
      dockerfile: Dockerfile
    container_name: dagster_daemon
    restart: always
    environment:
      DAGSTER_POSTGRES_USER: ${POSTGRES_USER}
      DAGSTER_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DAGSTER_POSTGRES_DB: ${POSTGRES_DB}
      
      BLIZZARD_CLIENT_ID: ${BLIZZARD_CLIENT_ID}
      BLIZZARD_CLIENT_SECRET: ${BLIZZARD_CLIENT_SECRET}

      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./data_pipeline:/opt/dagster/app
    command: dagster-daemon run -w config/workspace.yaml
    depends_on:
      - postgres
      - minio
    networks:
      - data_network

  api:
    build:
      context: ./backend_api
      dockerfile: Dockerfile
    container_name: azeroth_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=5432
    volumes:
      - ./backend_api:/app
    depends_on:
      - postgres
    networks:
      - data_network

  dashboard:
    build: ./dashboard
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000
    volumes:
      - ./dashboard:/app
    networks:
      - data_network
volumes:
  postgres_data:
  minio_data:

networks:
  data_network:
    driver: bridge